debugged the IVCAP registration proccess 'make service-register'

diff --git a/examples/local_ivcap_tool/Makefile b/examples/local_ivcap_tool/Makefile
--- a/examples/local_ivcap_tool/Makefile
+++ b/examples/local_ivcap_tool/Makefile
@@ -67,43 +67,12 @@ docker-build:
 SERVICE_IMG := ${DOCKER_DEPLOY}
 PUSH_FROM := ""
 
-docker-publish: docker-build
-	@echo "Publishing docker image '${DOCKER_TAG}'"
-	docker tag ${DOCKER_TAG_LOCAL} ${DOCKER_TAG}
-	sleep 1
-	$(eval size:=$(shell docker inspect ${DOCKER_TAG} --format='{{.Size}}' | tr -cd '0-9'))
-	$(eval imageSize:=$(shell expr ${size} + 0 ))
-	@echo "... imageSize is ${imageSize}"
-	@if [ ${imageSize} -gt 2000000000 ]; then \
-		set -e ; \
-		echo "preparing upload from local registry"; \
-		if [ -z "$(shell docker ps -a -q -f name=registry-2)" ]; then \
-			echo "running local registry-2"; \
-			docker run --restart always -d -p 8081:5000 --name registry-2 registry:2 ; \
-		fi; \
-		docker tag ${DOCKER_TAG} localhost:8081/${DOCKER_TAG} ; \
-		docker push localhost:8081/${DOCKER_TAG} ; \
-		$(MAKE) PUSH_FROM="localhost:8081/" docker-publish-common ; \
-	else \
-		$(MAKE) PUSH_FROM="--local " docker-publish-common; \
-	fi
-
-docker-publish-common:
-	$(eval log:=$(shell ivcap package push --force ${PUSH_FROM}${DOCKER_TAG} | tee /dev/tty))
-	$(eval registry := $(shell echo ${DOCKER_REGISTRY} | cut -d'/' -f1))
-	$(eval SERVICE_IMG := $(shell echo ${log} | sed -E "s/.*([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*) pushed/\1/"))
-	@if [ "${SERVICE_IMG}" == "" ] || [ "${SERVICE_IMG}" == "${DOCKER_TAG}" ]; then \
-		echo "service package push failed"; \
-		exit 1; \
-	fi
-	@echo ">> Successfully published '${DOCKER_TAG}' as '${SERVICE_IMG}'"
-
-service-register: docker-publish
+service-register: tool-register
 	$(eval account_id=$(shell ivcap context get account-id))
 	@if [[ ${account_id} != urn:ivcap:account:* ]]; then echo "ERROR: No IVCAP account found"; exit -1; fi
-	$(eval service_id:=urn:ivcap:service:$(shell python3 -c 'import uuid; print(uuid.uuid5(uuid.NAMESPACE_DNS, \
+	@$(eval service_id:=urn:ivcap:service:$(shell python3 -c 'import uuid; print(uuid.uuid5(uuid.NAMESPACE_DNS, \
         "${SERVICE_NAME}" + "${account_id}"));'))
-	$(eval image:=$(shell ivcap package list ${DOCKER_TAG}))
+	@$(eval image:=$(shell ivcap package list ${DOCKER_TAG}))
 	@if [[ -z "${image}" ]]; then echo "ERROR: No uploaded docker image '${DOCKER_TAG}' found"; exit -1; fi
 	@echo "ServiceID: ${service_id}"
 	cat ${PROJECT_DIR}/${IVCAP_SERVICE_FILE} \
@@ -111,14 +80,33 @@ service-register: docker-publish
 	| sed 's|#SERVICE_ID#|${service_id}|' \
   | ivcap aspect update ${service_id} -f - --timeout 600
 
-tool-register:
+tool-register: docker-publish
 	$(eval account_id=$(shell ivcap context get account-id))
 	@if [[ ${account_id} != urn:ivcap:account:* ]]; then echo "ERROR: No IVCAP account found"; exit -1; fi
 	$(eval service_id:=urn:ivcap:service:$(shell python3 -c 'import uuid; print(uuid.uuid5(uuid.NAMESPACE_DNS, \
         "${SERVICE_NAME}" + "${account_id}"));'))
-	@echo "ServiceID: ${service_id}"
+	$(eval tool_id:=$(shell grep "\"id\":" ${PROJECT_DIR}/${TOOL_SCHEMA_FILE} | cut -d\" -f 4 ))
+	@echo "DEBUG: ToolID: ${tool_id} ServiceID: ${service_id}"
 	cat ${PROJECT_DIR}/${TOOL_SCHEMA_FILE} \
 	| sed 's|#SERVICE_ID#|${service_id}|' \
-  | ivcap aspect update ${service_id} -f - --timeout 600
+	| ivcap aspect update ${service_id} -f - --timeout 600
+
+docker-publish: docker-build
+	@echo "INFO: Publishing docker image '${DOCKER_TAG}'"
+	docker tag ${DOCKER_NAME} ${DOCKER_TAG}
+	$(eval size:=$(shell docker inspect ${DOCKER_NAME} --format='{{.Size}}' | tr -cd '0-9'))
+	$(eval imageSize:=$(shell expr ${size} + 0 ))
+	@echo "... imageSize is ${imageSize}"
+	@$(MAKE) PUSH_FROM="--local " docker-publish-common
+
+docker-publish-common:
+	$(eval log:=$(shell ivcap package push --force ${PUSH_FROM}${DOCKER_TAG} | tee /dev/tty))
+	$(eval SERVICE_IMG := $(shell echo ${log} | sed -E "s/.*([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*) pushed/\1/"))
+	@if [ "${SERVICE_IMG}" == "" ] || [ "${SERVICE_IMG}" == "${DOCKER_TAG}" ]; then \
+		echo "service package push failed"; \
+		exit 1; \
+	fi
+	@echo "INFO: Successfully published '${DOCKER_TAG}' as '${SERVICE_IMG}'"
+
 
 FORCE:
